feat: Add `test_holiday_checker.py`
JAL-D35/stock-forest pull request #8
Opened 2023-11-16 11:30 UTC by DevSmapy

### What is this PR?

- Add `test_holiday_checker.py` for testing

2023-11-20 12:43 UTC, hashfunc requested changes

2023-11-20 12:43 UTC, hashfunc commented on pyproject.toml
> +pytest = "^7.4.3"
P3. `pytest`는 다른 그룹으로 설정하는 것이 좋을 것 같아요.

2023-11-20 12:43 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +BASE_DATETIME = datetime(2023, 11, 13)
P1. `BASE_DATETIME`은 코드에서 사용되는 곳이 없어요.

2023-11-20 12:43 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +    ],  # yapf: disable
P1. 불필요한 주석이 있어요.

2023-11-20 12:43 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +        (datetime(2023, 11, 19), True),
P2. 이 값들이 왜 테스트에 사용되었는지 이유를 명확하게 알 수 있으면 좋겠어요.

2023-11-20 12:43 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +        ("20231119", date(2023, 11, 19)),
P2. 이 값들이 왜 테스트에 사용되었는지 이유를 명확하게 알 수 있으면 좋겠어요.

2023-11-21 11:11 UTC, DevSmapy commented on data_loader/test_holiday_checker.py
> +BASE_DATETIME = datetime(2023, 11, 13)
`BASE_DATE`로 변수명 수정을 했습니다.

해당 변수는 테스트에 사용되는 변수이기 때문에 임의의 날짜를 선정하기 위해서 random 패키지의 randint를 사용하여 임의의 날짜가 `BASE_DATE`에 정의 될 수 있도록 하였습니다.

2023-11-21 11:13 UTC, DevSmapy commented on data_loader/test_holiday_checker.py
> +        (datetime(2023, 11, 19), True),
`BASE_DATE`와 `timedelta`를 사용하여 임의의 연속된 7일의 날짜를 생성하도록 수정하였습니다.

연속된 7일의 날짜를 선택한 이유는 `Weekday.is_weekend`는 요일을 판별하도록 하는 부분이기 때문에 모든 요일을 확인할 수 있도록 임의의 날짜를 선정한 뒤, 연속된 7일을 생성하여 모든 요일이 한번씩 나올 수 있도록 수정하였습니다.

2023-11-21 12:36 UTC, DevSmapy commented on data_loader/test_holiday_checker.py
> +        ("20231119", date(2023, 11, 19)),
임의의 날짜인 `BASE_DATE`를 사용하는 테스트로 수정하였습니다.

테스트 횟수도 7번의 테스트에서 `BASE_DATE`에 대한 한번으로 수정하였는데, 이는 임의의로 정해진 날짜에 대해서 해당 함수가 성립할 수 있는지 확인하는 목적이기 때문에 한번으로 수정하였습니다.

2023-11-21 13:12 UTC, hashfunc requested changes

2023-11-21 13:12 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +BASE_DATE = datetime(randint(0, 2023), randint(1, 12), randint(1, 31))
P3. `BASE_DATE`의 타입이 **datetime**이 될텐데 이름이 BASE_DATE이 되는게 좋지 않은 것 같아요.

2023-11-21 13:12 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +BASE_DATE = datetime(randint(0, 2023), randint(1, 12), randint(1, 31))
P3. 날짜가 무작위라면 원하는 결과를 얻기가 어려워지는데 어떤 이유로 날짜를 무작위로 지정하여 테스트하게 되었나요?

2023-11-21 13:12 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +def test_is_weekend(input_date: datetime) -> Optional[bool]:
P1. `test_is_weekend` 함수는 반환값이 없는데 Optional[bool] 타입으로 설정한 이유는 무엇인가요?

2023-11-21 13:12 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +def test_convert_to_date() -> Optional[bool]:
P1. `test_is_weekend` 함수는 반환값이 없는데 Optional[bool] 타입으로 설정한 이유는 무엇인가요?

2023-11-21 13:12 UTC, hashfunc commented on data_loader/test_holiday_checker.py
> +    assert Weekday.is_weekend(input_date) == (input_date.weekday() > 4)  # 4 is Friday
P2. 테스트 코드가 대상 함수와 거의 동일한데, 이렇게 테스트하는게 좋은 방향인지 고민이 필요할 것 같아요.

2023-11-25 06:22 UTC, hashfunc approved these changes
LGTM

2023-11-25 06:23 UTC, merged